# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)

# platform :ios do
#   desc "Description of what the lane does"
#   lane :custom_lane do
#     # add actions here: https://docs.fastlane.tools/actions
#   end
# end


# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :metrics do

    scan(scheme: "HashimGit", 
      code_coverage: true, 
      derived_data_path: "./DerivedData", 
      output_directory: "./sonar-reports",
      devices: "iPhone 6s")
     
    slather(cobertura_xml: true, 
      jenkins: true, 
      scheme: "HashimGit", 
      build_directory: "./DerivedData", 
      output_directory: "./sonar-reports", 
      proj: "./HashimGit.xcodeproj")

     swiftlint(output_file: "./sonar-reports/swiftlint.txt", 
      ignore_exit_status: true)

     sonar
end
end