name: Swift

on:
  push:
    branches: [ master , github, jenkins]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.app
      
    - name: Build and test
      run: xcodebuild clean build test -project HashimGit.xcodeproj -scheme "HashimGit" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.2.1

    - name: GitHub Action for SwiftLint (Only files changed in the PR)
      uses: mhhashim/action-swiftlint
      env:
        DIFF_BASE: ${{ github.base_ref }}
